<?php

use yii\db\Migration;

/**
 * Class m240807_050002_insert_rbac_data
 * Handles inserting RBAC initial data for roles and permissions.
 */
class m250807_200102_insert_rbac_data extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $time = time();

        // Insert Permissions & Roles into auth_item
        $this->batchInsert('{{%auth_item}}', ['name', 'type', 'description', 'created_at', 'updated_at'], [
            // Roles
            ['admin', 1, 'Admin', $time, $time],
            ['guest', 1, 'Guest', $time, $time],
            ['owner', 1, 'Company Owner', $time, $time],
            ['participant', 1, 'Participant', $time, $time],
            ['regular', 1, 'Regular', $time, $time],
            // Permissions
            ['create-assessment', 2, 'Create Assessment', $time, $time],
            ['create-asset', 2, 'Create Asset', $time, $time],
            ['create-assetcategory', 2, 'Create Asset Category', $time, $time],
            ['create-employment', 2, 'Create Employment', $time, $time],
            ['create-group', 2, 'Create Group', $time, $time],
            ['create-ispring-master', 2, 'Create Ispring Master', $time, $time],
            ['create-ispring-transaction', 2, 'Create Ispring Transaction', $time, $time],
            ['create-master', 2, 'Create Master', $time, $time],
            ['create-office', 2, 'Create Office', $time, $time],
            ['create-officemedia', 2, 'Create Office Media', $time, $time],
            ['create-page', 2, 'Create Page', $time, $time],
            ['create-participant', 2, 'Create Participant', $time, $time],
            ['create-period', 2, 'Create Period', $time, $time],
            ['create-profile', 2, 'Create Profile', $time, $time],
            ['create-room', 2, 'Create Room', $time, $time],
            ['create-schedule', 2, 'Create Schedule', $time, $time],
            ['create-scheduledetail', 2, 'Create Schedule Detail', $time, $time],
            ['create-scheduletoken', 2, 'Create Schedule Token', $time, $time],
            ['create-staff', 2, 'Create Staff', $time, $time],
            ['create-subject', 2, 'Create Subject', $time, $time],
            ['create-transaction', 2, 'Create Transaction', $time, $time],
            ['create-user-owner', 2, 'Create User Owner', $time, $time],
            ['create-user-regular', 2, 'Create User Regular', $time, $time],
            ['delete-assessment', 2, 'Delete Assessment', $time, $time],
            ['delete-asset', 2, 'Delete Asset', $time, $time],
            ['delete-assetcategory', 2, 'Delete Asset Category', $time, $time],
            ['delete-employment', 2, 'Delete Employment', $time, $time],
            ['delete-group', 2, 'Delete Group', $time, $time],
            ['delete-ispring-master', 2, 'Delete Ispring Master', $time, $time],
            ['delete-ispring-transaction', 2, 'Delete Ispring Transaction', $time, $time],
            ['delete-master', 2, 'Delete Master', $time, $time],
            ['delete-office', 2, 'Delete Office', $time, $time],
            ['delete-officemedia', 2, 'Delete Office Media', $time, $time],
            ['delete-page', 2, 'Delete Page', $time, $time],
            ['delete-participant', 2, 'Delete Participant', $time, $time],
            ['delete-period', 2, 'Delete Period', $time, $time],
            ['delete-profile', 2, 'Delete Profile', $time, $time],
            ['delete-room', 2, 'Delete Room', $time, $time],
            ['delete-schedule', 2, 'Delete Schedule', $time, $time],
            ['delete-scheduledetail', 2, 'Delete Schedule Detail', $time, $time],
            ['delete-scheduletoken', 2, 'Delete Schedule Token', $time, $time],
            ['delete-staff', 2, 'Delete Staff', $time, $time],
            ['delete-subject', 2, 'Delete Subject', $time, $time],
            ['delete-transaction', 2, 'Delete Transaction', $time, $time],
            ['index-assessment', 2, 'Index Assessment', $time, $time],
            ['index-asset', 2, 'Index Asset', $time, $time],
            ['index-assetcategory', 2, 'Index Asset Category', $time, $time],
            ['index-employment', 2, 'Index Employment', $time, $time],
            ['index-group', 2, 'Index Group', $time, $time],
            ['index-ispring-master', 2, 'Index Ispring Master', $time, $time],
            ['index-ispring-transaction', 2, 'Index Ispring Transaction', $time, $time],
            ['index-master', 2, 'Index Master', $time, $time],
            ['index-office', 2, 'Index Office', $time, $time],
            ['index-officemedia', 2, 'Index Office Media', $time, $time],
            ['index-page', 2, 'Index Page', $time, $time],
            ['index-participant', 2, 'Index Participant', $time, $time],
            ['index-period', 2, 'Index Period', $time, $time],
            ['index-profile', 2, 'Index Profile', $time, $time],
            ['index-room', 2, 'Index Room', $time, $time],
            ['index-schedule', 2, 'Index Schedule', $time, $time],
            ['index-scheduledetail', 2, 'Index Schedule Detail', $time, $time],
            ['index-scheduletoken', 2, 'Index Schedule Token', $time, $time],
            ['index-staff', 2, 'Index Staff', $time, $time],
            ['index-subject', 2, 'Index Subject', $time, $time],
            ['index-transaction', 2, 'Index Transaction', $time, $time],
            ['report-assessment', 2, 'Report Assessment', $time, $time],
            ['report-asset', 2, 'Report Asset', $time, $time],
            ['report-assetcategory', 2, 'Report Asset Category', $time, $time],
            ['report-group', 2, 'Report Group', $time, $time],
            ['report-ispring-master', 2, 'Report Ispring Master', $time, $time],
            ['report-ispring-transaction', 2, 'Report Ispring Transaction', $time, $time],
            ['report-master', 2, 'Report Master', $time, $time],
            ['report-participant', 2, 'Report Participant', $time, $time],
            ['report-period', 2, 'Report Period', $time, $time],
            ['report-room', 2, 'Report Room', $time, $time],
            ['report-schedule', 2, 'Report Schedule', $time, $time],
            ['report-scheduledetail', 2, 'Report Schedule Detail', $time, $time],
            ['report-scheduletoken', 2, 'Report Schedule Token', $time, $time],
            ['report-subject', 2, 'Report Subject', $time, $time],
            ['report-transaction', 2, 'Report Transaction', $time, $time],
            ['update-assessment', 2, 'Update Assessment', $time, $time],
            ['update-asset', 2, 'Update Asset', $time, $time],
            ['update-assetcategory', 2, 'Update Asset Category', $time, $time],
            ['update-employment', 2, 'Update Employment', $time, $time],
            ['update-group', 2, 'Update Group', $time, $time],
            ['update-ispring-master', 2, 'Update Ispring Master', $time, $time],
            ['update-ispring-transaction', 2, 'Update Ispring Transaction', $time, $time],
            ['update-master', 2, 'Update Master', $time, $time],
            ['update-office', 2, 'Update Office', $time, $time],
            ['update-officemedia', 2, 'Update Office Media', $time, $time],
            ['update-page', 2, 'Update Page', $time, $time],
            ['update-participant', 2, 'Update Participant', $time, $time],
            ['update-period', 2, 'Update Period', $time, $time],
            ['update-profile', 2, 'Update Profile', $time, $time],
            ['update-room', 2, 'Update Room', $time, $time],
            ['update-schedule', 2, 'Update Schedule', $time, $time],
            ['update-scheduledetail', 2, 'Update Schedule Detail', $time, $time],
            ['update-scheduletoken', 2, 'Update Schedule Token', $time, $time],
            ['update-staff', 2, 'Update Staff', $time, $time],
            ['update-subject', 2, 'Update Subject', $time, $time],
            ['update-transaction', 2, 'Update Transaction', $time, $time],
            ['view-assessment', 2, 'View Assessment', $time, $time],
            ['view-asset', 2, 'View Asset', $time, $time],
            ['view-assetcategory', 2, 'View Asset Category', $time, $time],
            ['view-employment', 2, 'View Employment', $time, $time],
            ['view-group', 2, 'View Group', $time, $time],
            ['view-ispring-master', 2, 'View Ispring Master', $time, $time],
            ['view-ispring-transaction', 2, 'View Ispring Transaction', $time, $time],
            ['view-master', 2, 'View Master', $time, $time],
            ['view-office', 2, 'View Office', $time, $time],
            ['view-officemedia', 2, 'View Office Media', $time, $time],
            ['view-page', 2, 'View Page', $time, $time],
            ['view-participant', 2, 'View Participant', $time, $time],
            ['view-period', 2, 'View Period', $time, $time],
            ['view-profile', 2, 'View Profile', $time, $time],
            ['view-room', 2, 'View Room', $time, $time],
            ['view-schedule', 2, 'View Schedule', $time, $time],
            ['view-scheduledetail', 2, 'View Schedule Detail', $time, $time],
            ['view-scheduletoken', 2, 'View Schedule Token', $time, $time],
            ['view-staff', 2, 'View Staff', $time, $time],
            ['view-subject', 2, 'View Subject', $time, $time],
            ['view-transaction', 2, 'View Transaction', $time, $time],
        ]);

        // Insert Child Items into auth_item_child
        $this->batchInsert('{{%auth_item_child}}', ['parent', 'child'], [
            ['create-ispring-transaction', 'create-assessment'],
            ['create-transaction', 'create-asset'],
            ['create-master', 'create-assetcategory'],
            ['create-master', 'create-employment'],
            ['create-ispring-master', 'create-group'],
            ['admin', 'create-ispring-master'],
            ['owner', 'create-ispring-master'],
            ['admin', 'create-ispring-transaction'],
            ['owner', 'create-ispring-transaction'],
            ['regular', 'create-ispring-transaction'],
            ['admin', 'create-master'],
            ['owner', 'create-master'],
            ['create-master', 'create-office'],
            ['create-master', 'create-officemedia'],
            ['create-master', 'create-page'],
            ['create-ispring-master', 'create-participant'],
            ['create-ispring-master', 'create-period'],
            ['create-master', 'create-profile'],
            ['create-ispring-master', 'create-room'],
            ['create-ispring-master', 'create-schedule'],
            ['create-ispring-master', 'create-scheduledetail'],
            ['create-ispring-master', 'create-scheduletoken'],
            ['create-master', 'create-staff'],
            ['create-ispring-master', 'create-subject'],
            ['admin', 'create-transaction'],
            ['owner', 'create-transaction'],
            ['regular', 'create-transaction'],
            ['index-transaction', 'create-user-regular'],
            ['delete-ispring-transaction', 'delete-assessment'],
            ['delete-transaction', 'delete-asset'],
            ['delete-master', 'delete-assetcategory'],
            ['delete-master', 'delete-employment'],
            ['delete-ispring-master', 'delete-group'],
            ['admin', 'delete-ispring-master'],
            ['owner', 'delete-ispring-master'],
            ['admin', 'delete-ispring-transaction'],
            ['owner', 'delete-ispring-transaction'],
            ['admin', 'delete-master'],
            ['owner', 'delete-master'],
            ['delete-master', 'delete-office'],
            ['delete-master', 'delete-officemedia'],
            ['delete-master', 'delete-page'],
            ['delete-ispring-master', 'delete-participant'],
            ['delete-ispring-master', 'delete-period'],
            ['delete-master', 'delete-profile'],
            ['delete-ispring-master', 'delete-room'],
            ['delete-ispring-master', 'delete-schedule'],
            ['delete-ispring-master', 'delete-scheduledetail'],
            ['delete-ispring-master', 'delete-scheduletoken'],
            ['delete-master', 'delete-staff'],
            ['delete-ispring-master', 'delete-subject'],
            ['admin', 'delete-transaction'],
            ['owner', 'delete-transaction'],
            ['regular', 'delete-transaction'],
            ['index-ispring-transaction', 'index-assessment'],
            ['guest', 'index-asset'],
            ['index-transaction', 'index-asset'],
            ['index-master', 'index-assetcategory'],
            ['index-master', 'index-employment'],
            ['index-ispring-master', 'index-group'],
            ['admin', 'index-ispring-master'],
            ['owner', 'index-ispring-master'],
            ['regular', 'index-ispring-master'],
            ['admin', 'index-ispring-transaction'],
            ['owner', 'index-ispring-transaction'],
            ['regular', 'index-ispring-transaction'],
            ['admin', 'index-master'],
            ['owner', 'index-master'],
            ['regular', 'index-master'],
            ['index-master', 'index-office'],
            ['index-master', 'index-officemedia'],
            ['index-master', 'index-page'],
            ['index-ispring-master', 'index-participant'],
            ['index-ispring-master', 'index-period'],
            ['index-master', 'index-profile'],
            ['index-ispring-master', 'index-room'],
            ['index-ispring-master', 'index-schedule'],
            ['index-ispring-master', 'index-scheduledetail'],
            ['index-ispring-master', 'index-scheduletoken'],
            ['index-master', 'index-staff'],
            ['index-ispring-master', 'index-subject'],
            ['admin', 'index-transaction'],
            ['owner', 'index-transaction'],
            ['regular', 'index-transaction'],
            ['report-ispring-transaction', 'report-assessment'],
            ['report-transaction', 'report-asset'],
            ['report-master', 'report-assetcategory'],
            ['report-ispring-master', 'report-group'],
            ['admin', 'report-ispring-master'],
            ['owner', 'report-ispring-master'],
            ['regular', 'report-ispring-master'],
            ['admin', 'report-ispring-transaction'],
            ['owner', 'report-ispring-transaction'],
            ['regular', 'report-ispring-transaction'],
            ['admin', 'report-master'],
            ['owner', 'report-master'],
            ['report-ispring-master', 'report-participant'],
            ['report-ispring-master', 'report-period'],
            ['report-ispring-master', 'report-room'],
            ['report-ispring-master', 'report-schedule'],
            ['report-ispring-master', 'report-scheduledetail'],
            ['report-ispring-master', 'report-scheduletoken'],
            ['report-ispring-master', 'report-subject'],
            ['admin', 'report-transaction'],
            ['owner', 'report-transaction'],
            ['regular', 'report-transaction'],
            ['update-ispring-transaction', 'update-assessment'],
            ['update-transaction', 'update-asset'],
            ['update-master', 'update-assetcategory'],
            ['update-master', 'update-employment'],
            ['update-ispring-master', 'update-group'],
            ['admin', 'update-ispring-master'],
            ['owner', 'update-ispring-master'],
            ['admin', 'update-ispring-transaction'],
            ['owner', 'update-ispring-transaction'],
            ['admin', 'update-master'],
            ['owner', 'update-master'],
            ['update-master', 'update-office'],
            ['update-master', 'update-officemedia'],
            ['update-master', 'update-page'],
            ['update-ispring-master', 'update-participant'],
            ['update-ispring-master', 'update-period'],
            ['regular', 'update-profile'],
            ['update-master', 'update-profile'],
            ['update-ispring-master', 'update-room'],
            ['update-ispring-master', 'update-schedule'],
            ['update-ispring-master', 'update-scheduledetail'],
            ['update-ispring-master', 'update-scheduletoken'],
            ['update-master', 'update-staff'],
            ['update-ispring-master', 'update-subject'],
            ['admin', 'update-transaction'],
            ['owner', 'update-transaction'],
            ['regular', 'update-transaction'],
            ['view-ispring-transaction', 'view-assessment'],
            ['guest', 'view-asset'],
            ['view-transaction', 'view-asset'],
            ['view-master', 'view-assetcategory'],
            ['view-master', 'view-employment'],
            ['view-ispring-master', 'view-group'],
            ['admin', 'view-ispring-master'],
            ['owner', 'view-ispring-master'],
            ['regular', 'view-ispring-master'],
            ['admin', 'view-ispring-transaction'],
            ['owner', 'view-ispring-transaction'],
            ['regular', 'view-ispring-transaction'],
            ['admin', 'view-master'],
            ['owner', 'view-master'],
            ['regular', 'view-master'],
            ['view-master', 'view-office'],
            ['view-master', 'view-officemedia'],
            ['view-master', 'view-page'],
            ['view-ispring-master', 'view-participant'],
            ['view-ispring-master', 'view-period'],
            ['regular', 'view-profile'],
            ['view-master', 'view-profile'],
            ['view-ispring-master', 'view-room'],
            ['view-ispring-master', 'view-schedule'],
            ['view-ispring-master', 'view-scheduledetail'],
            ['view-ispring-master', 'view-scheduletoken'],
            ['view-master', 'view-staff'],
            ['view-ispring-master', 'view-subject'],
            ['admin', 'view-transaction'],
            ['owner', 'view-transaction'],
            ['regular', 'view-transaction'],
        ]);

        // Assign admin role to user with id 1
        $this->insert('{{%auth_assignment}}', [
            'item_name' => 'admin',
            'user_id' => '1',
            'created_at' => $time,
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        // Hapus data yang ditambahkan
        $this->delete('{{%auth_assignment}}', ['user_id' => '1', 'item_name' => 'admin']);
        $this->delete('{{%auth_item_child}}');
        $this->delete('{{%auth_item}}');

        echo "m240807_050002_insert_rbac_data was reverted.\n";
    }
}