<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(not set)' => '',
    'A password will be generated automatically if not provided' => '',
    'Account details' => '',
    'Are you sure you want to block this user?' => '',
    'Are you sure you want to confirm this user?' => '',
    'Are you sure you want to delete this user?' => '',
    'Are you sure you want to switch to this user for the rest of this Session?' => '',
    'Are you sure you want to unblock this user?' => '',
    'Are you sure?' => '',
    'Assignments' => '',
    'Become this user' => '',
    'Block' => '',
    'Block status' => '',
    'Blocked at {0, date, MMMM dd, YYYY HH:mm}' => '',
    'Confirm' => '',
    'Confirmation' => '',
    'Confirmation status' => '',
    'Confirmed' => '',
    'Confirmed at {0, date, MMMM dd, YYYY HH:mm}' => '',
    'Continue' => '',
    'Create' => '',
    'Create a user account' => '',
    'Credentials will be sent to the user by email' => '',
    'Delete' => '',
    'Didn\'t receive confirmation message?' => '',
    'Don\'t have an account? Sign up!' => '',
    'Forgot password?' => '',
    'Generate and send new password to user' => '',
    'If you already registered, sign in and connect this account on settings page' => '',
    'In order to finish your registration, we need you to enter following fields' => '',
    'Information' => '',
    'Manage users' => '',
    'Never' => '',
    'New permission' => '',
    'New role' => '',
    'New user' => '',
    'Not blocked' => '',
    'Password' => '',
    'Password is not necessary because the module is in DEBUG mode.' => '',
    'Permissions' => '',
    'Profile details' => '',
    'Register a new membership' => '',
    'Registration IP' => '',
    'Registration time' => '',
    'Request new confirmation message' => '',
    'Roles' => '',
    'Save' => '',
    'Sign in' => '',
    'Sign in as Admin' => '',
    'Sign up' => '',
    'Unblock' => '',
    'Unconfirmed' => '',
    'Update' => '',
    'Update user account' => '',
    'Users' => '',
    'You can assign multiple roles or permissions to user by using the form below' => '',
    'resend' => '',
    'signin' => '',
    '{0, date, MMMM dd, YYYY HH:mm}' => '',
    '<label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">Email</label>' => '@@@@',
    '<label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">Password</label>' => '@@@@',
    '<label class="g-color-gray-dark-v2 g-font-weight-600 g-font-size-13">Username</label>' => '@@@@',
    'Can not updated blank password.' => '@@@@',
    'Finish' => '@@@@',
    'New rule' => '@@@@',
    'Profile Login' => '@@@@',
    'Recover your password' => '@@@@',
    'Reset your password' => '@@@@',
    'Rules' => '@@@@',
    'This email address has already been taken' => '@@@@',
    'This username has already been taken' => '@@@@',
    'User password has been updated' => '@@@@',
    'signup' => '@@@@',
];
